### ISSUE TITLE
Add option to fetch PIDs etc for other kinds of parent object (beyond Collection)

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#20]
I'm trying to use islandora_datastream_crud to fix up some Newspaper Page objects where some failed to generate derivatives. Parent objects right now, as far as I can tell, require the Collection CModel. I would love to instead be able to use the parent newspaper (ufv:255) as a parameter in the command - i.e. rather than --collection=(whatever), something more general: --parent=ufv:255 (or even parent_newspaper=ufv:255 if the general approach isn't possible).

**Comment by mjordan** [comment]
I hadn't thought of that use case, but would a combination of `--content_model=islandora:newspaperPageCModel` and `--namespace=ufv` get you what you want?

**Comment by mjordan** [comment]
You can also use arbitrary Solr queries to get a list of PIDS, using the `--solr_query` option. It hasn't been widely tested with complex queries but it's worth a try. How about:

`--solr_query="RELS_EXT_isMemberOf_uri_s:info\:fedora/ufv\:255"`

**Comment by bondjimbond** [comment]
Yes, your first comment is my planned approach; should do the trick. But it would be a handy config option if you got the chance. Particularly in case of a collection having multiple different newspapers, and you only want to work with one newspaper's pages.

Also: just had a look at a Newspaper Page RELS-EXT. Turns out they are not members of collections, so you couldn't even narrow down if newspapers were in different collections.

**Comment by mjordan** [comment]
Problem is "parent" can mean several specific relationships in Islandora. In addition to isMemberOfCollection, we have:

* isMemberOf (newspaper pages)
* isConstituentOf (children of compound objects)

I'm not sure enhancing the `--parent` option would work without some inspection of content models. Maybe replace `--parent` with `--isMemberOfCollection`, `--isMemberOf`, and `--isConstituentOf`?

Another approach would be to search for the PID of the newspaper in the `ancestors_ms` field, if your Solr index has that field.

**Comment by bondjimbond** [comment]
I like keeping it simple. An option for each relationship (isMemberOfCollection, isMemberOf, isConstituentOf) is good.

Also suggest keeping the commands simple, as is currently done with the "--collection" parameter.

Suggestions:
Collection: --collection
isMemberOf: --newspaper_parent, or --member_of
isConstituentOf: --compound_parent (or something like that)

If there are other kinds of CModels with these relationships (e.g. books, serials), more general names (like member_of) would be good.

**Comment by mjordan** [comment]
Sounds good. Book pages also use isMemberOf.

I'll add these on the weekend. Thanks for opening this issue.

**Comment by mjordan** [comment]
Never did anything about this. Will do so however.

**Comment by bondjimbond** [comment]
Any progress on this? I'm thinking about further use cases/issues to consider.

Current situation: I need to delete all the OBJ files from the Page objects within a set of Books within a certain collection (and not any books that might be outside of that collection). Since Pages aren't part of collections, is it even possible to get a list of PIDs for pages that belong to any books that belong to a particular collection? 

I'm not sure you could even get at that with a Solr search... I've tried, looking at Solr fields for a Newspaper Page object, but while the Newspaper Issue is included in a field, the collection in which the newspaper lives is not.

**Comment by mjordan** [comment]
@bondjimbond sorry, been tied up with other things like #34 and #17. If the PID list is not achievable via a potentially complex Solr query, we could look at direct Resource Index/SPARQL queries, but to be honest, I'd rather not go there. However, don't forget that the PID list can come from anywhere, all it needs is some PIDS.... I know that advice is of little use but if you can get a list of PIDs from Solr Views, for example, you can use it as input to CRUD.

**Comment by mjordan** [comment]
Heh, now that I think of it, we could make the function that fetches PIDS hookable, so writers of code could create their own crazy implementations if they wanted. But that's probably overkill.

**Comment by bondjimbond** [comment]
PR #49 addresses this need; @mjordan please let me know if there's anything needed before that pull is mergeable.

**Comment by mjordan** [comment]
Super, thanks. I won't have time to test today or tomorrow, but will have time on the weekend.
