### ISSUE TITLE
"Cancel" doesn't actually cancel in delete_datastreams

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#21]
Kind of a major issue...

When running islandora_datastream_crud_delete_datastreams, a warning comes up: 

> You are about to delete (purge) the PDF datastream from a set of objects in your repository. This action cannot be undone. Do you want to want to continue? (y/n)

If you  choose "n", a message tells you "Exiting, no datastreams deleted" - but the datastreams are deleted regardless.

Sample command and output:

`brandonw@bceln2:/var/www/drupal7/sites$ drush islandora_datastream_crud_delete_datastreams -u 1 --dsid=PDF --pid_file=/var/www/drupal7/sites/newspaperpids.txt`

> You are about to delete (purge) the PDF datastream from a set of objects in your repository. This action cannot be undone. Do you want to want to continue? (y/n): n

> Exiting, no datastreams deleted.                                     [cancel]

> PDF datastream purged from object ufv:895                            [ok]

> PDF datastream purged from object ufv:932                            [ok]

> PDF datastream purged from object ufv:46                             [ok]

> PDF datastream purged from object ufv:912                            [ok]

> PDF datastream purged from object ufv:826                            [ok]

> PDF datastream purged from object ufv:641                            [ok]

> PDF datastream purged from object ufv:678                            [ok]

> (etc...)

Checking a few of the PIDs tells me that these are not just false confirmation messages; the PDF datastream has indeed been deleted from each of these objects. (Luckily, in my case, I really did want to delete the datastreams; I opted to cancel only due to last-minute paranoia.)

**Comment by mjordan** [comment]
Yikes. Thanks for catching this @bondjimbond. Looks like I need to explicitly `exit` [after calling](https://github.com/mjordan/islandora_datastream_crud/blob/7.x/islandora_datastream_crud.drush.inc#L403) the`drush_user_abort()` function despite this function's [documentation](http://www.drupalcontrib.org/api/drupal/contributions!drush!includes!drush.inc/function/drush_user_abort/7). Will fix today.

**Comment by mjordan** [comment]
@bondjimbond I've pushed up a fix. Can you do a quick test on the issue-21 branch and if it works as expected now I'll merge it into 7.x.

**Comment by bondjimbond** [comment]
Tested, seems to work. Mergeable!

I noticed some other weirdness, however. I first tried deleting the DC datastream from a set of objects; this led to an error:

> WD islandora: Failed to purge datastream DC from unbc:105code: 500message:         [error]
> Error purging DC datastream from object unbc:105; details below.                   [error]
>                                                                                   [error]

So:
- Can't delete DC datastream; is this expected?
- "details below" doesn't print details below... appears to print a blank line where details should be.

**Comment by mjordan** [comment]
'Tis merged. Thanks!

WRT deleting the DC datastream, as far as I know Fedora won't let you do that. DC is required by Fedora. I may be wrong, but if that's the case, Datastream CURD can't delete it. I'll have to look into the message, but it might be coming from upstream in Islandora and not the Datastream CRUD code. If that's the case, I have no control over it.

**Comment by mjordan** [comment]
I'm going to close this issue since I've merged the fix. If I find that it's impossible to delete DC I'll update the README to that effect, and if I find that it is possible, I'll open a new issue. That OK?

**Comment by bondjimbond** [comment]
Problem is not with whether or not it can delete DC, just the error message (especially "Details below" with no details). Probably fine if it just says something like "DC datastream is required".
