### ISSUE TITLE
Better error messages for failures (delete_datastreams, maybe others)

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#24]
In the delete_datastreams function, attempting to delete a datastream that doesn't exist gives an ambiguous error:

> asdf datastream not purged from object unbc:1                        [error]

If the specified datastream doesn't exist, the message should say so. ("asdf datastream not found on object unbc:1")

**Comment by mjordan** [comment]
Thanks, I'll take a look.

**Comment by mjordan** [comment]
@bondjimbond I've added a check in the delete datastreams code for the presence of the specified datastream; if it's not present, drush shows an error like this:

`FOO datastream not found in object islandora:25                                                        [error]`

Will merge this now and close. If you find any other misleading messages, open a new issue and reference this one. Thanks for finding this.

**Comment by mjordan** [comment]
Merged with 4b27b065bf90cee9ec6816d7c0d801c0860b0c2d.
