### ISSUE TITLE
Add --silent parameter for "silent mode"

### ISSUE THREAD

**Issue by wgilling** [SFULibrary/islandora_datastream_crud#25]
This is for the web wrapper islandora_datastreams_io tool to be able to call islandora_datastream_crud commands without stalling because of the prompts to create folders, pushing datastreams to objects, regenerate derivatives, etc.  

In all cases, when run with the --silent parameter, the assumed answer is to proceed.

I am going to make a pull request to merge our "uls_customizations" branch that includes these changes.

**Comment by mjordan** [comment]
@bgilling Does using drush's `-y` option accomplish the same thing? E.g., `drush islandora_datastream_crud_fetch_datastreams --user=admin --pid_file=/tmp/imagepids.txt --dsid=MODS --datastreams_directory=/tmp/imagemods -y`? If so, we should stick with that, but if your `--silent` option does something else, let me know.

**Comment by mjordan** [comment]
Just checked out https://github.com/ulsdevteam/islandora_datastreams_io. I'm going to give it a spin, but at first glance, it looks awesome!

**Comment by wgilling** [comment]
Mark,

Using the "-y" switch seems to allow the same functionality, so it seems this pull request will not be needed.  I did not know that was a drush option.  I am replacing the "--silent" switch in my code with a "-y" for export / import and make sure it still works as expected.

Thanks for the tip on the "-y" switch.

Brian Gillingham

**Comment by mjordan** [comment]
Brian, can I close this issue and associated PR?

**Comment by wgilling** [comment]
Mark,

Yes indeed.  I modified my code to use the -y switch, so if you cloned it pull an update.

Let's go Pens! Game 6 tonight!  :)

Thanks!
Brian Gillingham



Sent from my Samsung phone


-------- Original message --------
