### ISSUE TITLE
nohup support?

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#27]
For large CRUD processes (e.g. generate derivatives for 1600 objects), keeping the terminal open for the entire process to run is a bit much. I tried using nohup for the drush command, but that failed because of the confirmation line:

> You are about to regenerate derivatives from the OBJ datastream for 1643 object(s) in your repository. This action cannot be undone. Do you want to want to continue? (y/n): Exiting, no derivatives generated.

Is there a way to use nohup and include the "y" to confirm, or some other way around staying connected through the whole thing?

**Comment by mjordan** [comment]
Try drush's `-y` option, e.g., `drush islandora_datastream_crud_push_datastreams -y --user=admin --datastreams_mimetype=image/jpeg --datastreams_source_directory=/tmp/imagemods_modified --datastreams_crud_log=/tmp/crud.log`

**Comment by bondjimbond** [comment]
Good idea! Wish I'd tried that before just hitting "y" with the terminal open.

I elected to cancel and try that way... Fingers crossed. If it works, would it be a good idea to document the -y option for nohup users?

**Comment by mjordan** [comment]
Done, at the end of the "Usage" section in the README.

**Comment by bondjimbond** [comment]
Great stuff! Thanks. My CRUD operation is running smoothly right now.

**Comment by mjordan** [comment]
Super.
