### ISSUE TITLE
Does not import any PID that contain period characters

### ISSUE THREAD

**Issue by wgilling** [SFULibrary/islandora_datastream_crud#30]
In the code before it calls the islandora_datastream_crud_dsfilename_to_pid function, the php pathinfo function is used to get the datatream ID value for later in the islandora_datastream_crud_push_datastream code.  This will damage the $ds_filename variable for use in the  islandora_datastream_crud_dsfilename_to_pid function because it calls pathinfo on the $ds_filename value, but if the PID actually contains a real period character, this will make the end of the PID value as well as the datastream ID fall off and not return the true correct PID value.

For example, a file contained in the zip file is "pitt_ais9830.01.03.0001_MODS.xml" ... but the pathinfo function to get the filename from a full path ALSO strips off any file extension... so it is actually working with "pitt_ais9830.01.03.0001_MODS" as the value in islandora_datastream_crud_dsfilename_to_pid.  The first thing this function does is to use pathinfo again on it to get the filename portion, and this time, it loses the new "extension" value of 0001_MODS from the working value.  It returns a bad PID value of pitt:ais9830.01.03 (instead of pitt:ais9830.01.03.0001). 

After I submit this issue, I will make a pull request that has my one line bugfix to address this.

**Comment by mjordan** [comment]
PR #32.

**Comment by mjordan** [comment]
@bgilling while looking at your code I found #33, which is not related to your code but has been a longstanding bug. I'm happy to merge your PR once you confirm that it solves the problem with periods (which I can't really verify).

**Comment by mjordan** [comment]
Resolved with e92d398c64899b3302b19d2a84086e87cee255d4.
