### ISSUE TITLE
Solr query examples in README?

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#44]
It'd be nice to see some examples for the solr_query parameter, as writing a raw Solr query by hand is not an easy thing to ask of someone.

I'm trying to use this to get at newspaper issue objects with the isMemberOf relationship to a particular newspaper; since there's no isMemberOf parameter, solr_query is the likeliest way to do it. But I can't seem to get it working.

**Comment by mjordan** [comment]
@bondjimbond excellent suggestion. There is one example at https://github.com/mjordan/islandora_datastream_crud/issues/20#issuecomment-289859938 but it would be good to provide more.

**Comment by bondjimbond** [comment]
Ah, thanks - I'd forgotten about that. That example would work just fine in the README

**Comment by mjordan** [comment]
May as well add a couple others too. I can take a crack at that.

**Comment by bondjimbond** [comment]
Thanks!
