### ISSUE TITLE
Clarifying generate_derivatives in the README

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#45]
It isn't clear whether islandora_datastream_crud_generate_derivatives works with any type of source DSID (including, particularly, a metadata DSID), or just the OBJ/PDF/etc.

In my use case, I have a set of objects for which I had batch edited the MODS file, but need to trigger a DC transform. Could I use islandora_datastream_crud_generate_derivatives using MODS as the source DSID, and would that trigger the DC derivative as desired? Or would it create a big mess?

**Comment by mjordan** [comment]
DC is not a derivative of MODS, in the Islandora sense of "derivatives" (i.e., Islandora doesn't use the derivative hooks to generate it). The "Updating DC datastreams by pushing other XML datastreams" in the README covers how to accomplish what you want to do.

**Comment by mjordan** [comment]
But if it's not clear, let me know.

**Comment by bondjimbond** [comment]
Good to know! ... Can you force update DC without actually pushing new XML datastreams, though?

**Comment by mjordan** [comment]
No. To use Datastream CRUD to do this, you'll need to re-fetch your MODS, then re-push them to trigger regeneration of your DC.
