### ISSUE TITLE
Add ability to delete versions of datastreams

### ISSUE THREAD

**Issue by mjordan** [SFULibrary/islandora_datastream_crud#53]
From discussion starting at https://groups.google.com/d/msg/islandora/q1udVKoh194/YJD_4ulqCAAJ.

**Comment by mjordan** [comment]
Thinking a command like this is suitable. In this case, it would delete version 0 (the current one) and 1 (the previous one): `drush islandora_datastream_crud_delete_datastream_versions --user=admin --dsid=FOO --versions=0,1 --pid_file=/tmp/delete_foo_versions_from_these_objects.txt`

This would require knowing which versions you want to delete. If use cases for knowing the created date on the version to delete come up, we can address them then.

**Comment by bondjimbond** [comment]
A case for this functionality has come up for me, as old versions of large derivative datastreams are cluttering up the repository. In my use case, I would like to delete *all but the current version* from a list of PIDs.

**Comment by mjordan** [comment]
@bondjimbond if you can test @patdunlavey's PR I'll merge it.

**Comment by mjordan** [comment]
Resolved with 4feafbf17d4c8bf576254179a94e8c15e331fb06.
