### ISSUE TITLE
generate_derivatives breaks down on extremely large files?

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#66]
Error when trying to generate derivatives:

> coh:1
> Aug 26, 2018 2:56:54 PM edu.harvard.hul.ois.jhove.JhoveBase init
> SEVERE: Testing SEVERE level
> Error on line 174 of jhove_image_to_fits.xslt:
>   XPTY0004: A sequence of more than one item is not allowed as the first operand of 'div'
> 2018-08-26 14:56:58 - ERROR - ToolBase:283 - Caught exception running tool: Jhove
> edu.harvard.hul.ois.fits.exceptions.FitsToolException: Jhove: Error converting output using /opt/fits/xml/jhove/jhove_image_to_fits.xslt (A sequence of more than one item is not allowed as the first operand of 'div')
>         at edu.harvard.hul.ois.fits.tools.ToolBase.transform(ToolBase.java:141)
>         at edu.harvard.hul.ois.fits.tools.jhove.Jhove.extractInfo(Jhove.java:163)
>         at edu.harvard.hul.ois.fits.tools.ToolBase.run(ToolBase.java:278)
>         at java.lang.Thread.run(Thread.java:748)
> SLF4J: The following set of substitute loggers may have been accessed
> SLF4J: during the initialization phase. Logging calls during this
> SLF4J: phase were not honored. However, subsequent logging calls to these
> SLF4J: loggers will work as normally expected.
> SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
> SLF4J: org.apache.tika.parser.ocr.TesseractOCRParser
> identify.im6: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/788.
> identify.im6: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/788.
> identify.im6: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/788.
> identify.im6: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/788.

The OBJs in question are in the range of 1.3 GB (which is insanely high for images, I know). Output seems to hang at this point -- no progress going beyond it.

**Comment by mjordan** [comment]
I'm not sure this craps out because of the size or because there are several errors with the TIFF. Datastream CRUD uses the same derivative generation code that the rest of Islandora does. If you load this monster TIFF into a new test object using drush, does it ingest and generate derivatives successfully or also crap out?

**Comment by bondjimbond** [comment]
Don't know. Looking like it's not a problem with the module, at any rate. Getting some funny errors though.

E_RECOVERABLE_ERROR encountered; aborting. To ignore recoverable     ^[[31;40m^[[1m[error]^[[0m
errors, run again with --no-halt-on-error
Drush command terminated abnormally due to an unrecoverable error.   ^[[31;40m^[[1m[error]^[[0m

**Comment by mjordan** [comment]
@bondjimbond I'm going to close this for now, you can reopen if you get any additional information.
