### ISSUE TITLE
New fetch_pids option: without_cmodel

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#73]
We have a --content_model option, but we don't have any way to _exclude_ a certain content model from a query without using a Solr query. Using Solr means sacrificing other important parameters (like --without_dsid), so this specific set of objects is very hard to reach.

**Comment by mjordan** [comment]
@bondjimbond thanks, this is a good improvement. I will test your PR within a couple of days.

**Comment by mjordan** [comment]
Merged with 0dd99fd350464f3f1ba6b11cd73e372ec4aed3bc.
