### ISSUE TITLE
without_dsid is getting stuff with that dsid

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#82]
Maybe something to do with our caching tools? But I'm finding a very annoying problem coming up -- I'm trying to regenerate derivatives for a bunch of objects that had failed to get derivatives started, so I'm running the following command:

`drush -u 1 islandora_datastream_crud_fetch_pids --without_dsid=JP2 --pid_file=/home/brandonw/no_jp2.txt --content_model=islandora:newspaperPageCModel`

I keep getting the same 1833 results back, many of which I had already generated JP2s for last week. These objects _have_ JP2s! Why is islandora_datastream_crud returning them?

**Comment by mjordan** [comment]
@bondjimbond can you see if you can replicate this behavior without the `--content_model=islandora:newspaperPageCModel` option? To see if it is interfering with the `--without_dsid` option. Also, check the Solr document for the objects that shouldn't be picked up to see if the list of DSIDs is accurate.

**Comment by bondjimbond** [comment]
haha... I've got too many results if I don't set a content model:

```
drush -u 1 islandora_datastream_crud_fetch_pids --without_dsid=JP2 --pid_file=/home/brandonw/no_jp2.txt
Killed
```

**Comment by mjordan** [comment]
Can you check the Solr documents of the objects that should not be retrieved? Fetch_pids queries Solr, so either Solr is out of date/inaccurate, or there is a problem with the query itself.

**Comment by bondjimbond** [comment]
Interesting... So object [terrace:33447](https://arcabc.ca/islandora/object/terrace:33447) has a JP2 datastream, but here's its Solr document...

```
    "fedora_datastreams_ms": [
        "AUDIT",
        "RELS-EXT",
        "OBJ",
        "OCR",
        "DC",
        "TN",
        "JPG"
```

How is it that that datastream isn't getting indexed?

**Comment by mjordan** [comment]
Sorry, I have no idea in your specific case. My general guess is that somehow, during indexing, JP2 did't get included in the DSID list. You might want to figure out how widespread the missing JP2 DSID is (maybe via a Solr query?) and report that to DGI to see if they can figure out what's going on.

**Comment by bondjimbond** [comment]
We've been hit hard by bots this week, so I suspect the interruptions might have stopped the index updates from taking place. I'll try regenerating just for that one object and see if Solr recognizes it.

**Comment by mjordan** [comment]
That sounds like a good idea.

**Comment by bondjimbond** [comment]
Regenerating on just the one object = success; JP2 added to Solr index. I'm not sure about the mechanics behind it, but I'm glad we sorted out the problem! Thanks for your help.
