### ISSUE TITLE
Documentation: issues with caching

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#85]
After much confusion and experimentation, I have discovered that a site that uses a lot of caching (in my case, Cloudflare) can have a lot of problems with the CRUD results.

The biggest issue I've found is that generating derivatives somehow does not update the index if you are doing so on a URI where caching is enabled. That is, if you generate derivatives to create a new datastream, the `fedora_datastreams_ms` field (and similar) does not get updated. However, if you run the same operation on a URI without such heavy caching, the item is reindexed just fine.

There's nothing we can actually do about it on the code side, but it would be good to document this so that confused people like myself can troubleshoot.

**Comment by mjordan** [comment]
@bondjimbond thanks for discovering this. Would you mind opening a PR to document this behavior?
