### ISSUE TITLE
CRUD push creating new "MODS.xml" datastream rather than new version of MODS

### ISSUE THREAD

**Issue by krebeck** [SFULibrary/islandora_datastream_crud#9]
This is an issue first mentioned here:  https://groups.google.com/d/msg/islandora/q1udVKoh194/LELtH89uCAAJ

The exact workflow was to run the following:
_drush islandora_datastream_crud_fetch_pids --user=admin --collection=auislandora:5025 --pid_file=/tmp/child_slides.txt_

_drush islandora_datastream_crud_fetch_datastreams --user=admin --pid_file=/tmp/child_slides.txt --dsid=MODS --datastreams_directory=/tmp/childslides_

I then made the necessary changes to the MODS.xml files that were output in the previous command.  These changes were approved and the MODS seemed fine.  Sample filenames to be pushed were: auislandora_11408_MODS.xml, auislandora_11429_MODS.xml, etc.  

Finally, I attempted to push them back to the islandora server with

_drush islandora_datastream_crud_push_datastreams --user=admin --datastreams_source_directory=/tmp/childslides_modified --datastreams_crud_log=/tmp/crud.log_

That is when I got the unexpected results mentioned in the post to Google Groups.

**Comment by mjordan** [comment]
Great, thanks. Possible to get some sample filenames for files in `/tmp/childslides` at the time you ran `islandora_datastream_crud_push_datastreams`?

**Comment by krebeck** [comment]
I just updated with some sample file names in /tmp/childslides_modified

auislandora_11407_MODS.xml
auislandora_11408_MODS.xml
auislandora_11409_MODS.xml

Aaron Krebeck
Digital Services Librarian
Washington Research Library Consortium
301-390-2040

**Comment by mjordan** [comment]
@krebeck I'll try to replicate and will report back. What commit are you running on?

**Comment by krebeck** [comment]
commit 46cdcc9da506bbb5a25a97e737e038d9aa6432be
Author: Mark Jordan mjordan@sfu.ca
Date:   Tue Apr 12 14:50:31 2016 +0000

Aaron Krebeck
Digital Services Librarian
Washington Research Library Consortium
301-390-2040

**Comment by mjordan** [comment]
Ah - the next commit, fd2f63dce2e8d21db0b6005e3c04f8dc7d707e2e, resolved #2, so that makes sense. Would you mind removing a couple of the unwanted MODS.xml datastreams, pulling in the latest chages to the CRUD code, and re-pushing the datastreams you removed? I recommend trying this on a small number, maybe just a couple, before going whole hog.

**Comment by mjordan** [comment]
@krebeck just checking in to see if the problem still exists after you've pulled in the most recent code updates.

**Comment by krebeck** [comment]
Sorry Mark, just getting around to this.  I have repeated the process in a
much smaller collection and it seems to be working great.  Thanks.  The
push created a new version of the MODS and it is the current version.

A

Aaron Krebeck
Digital Services Librarian
Washington Research Library Consortium
301-390-2040

**Comment by mjordan** [comment]
Excellent, OK to close?

**Comment by krebeck** [comment]
Sure thing. Go ahead.
