### ISSUE TITLE
Respect namespace restrictions

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_datastream_crud#91]
If running CRUD functions in a particular URI, I have found that that site's Solr namespace restrictions are not respected. e.g. if I run the query `drush -u 1 islandora_datastream_crud_fetch_pids --pid_file=/home/brandonw/bcrdh_version_delete.txt --solr_query="fedora_datastreams_mt:JP2 AND fedora_datastream_version_JP2_ID_ms:JP2.1" --uri=https://bcrdh.ca`, what I would hope to get is a list of PIDs that are accessible to the `https://bcrdh.ca` URI. Instead, it fetches all the PIDs without no regard for namespace filters.

I also found that if I run `islandora_datastream_crud_delete_datastreams` in a particular URI, I am able to delete datastreams from objects that should be inaccessible from that URI. e.g. running with `--uri=https://ufv.arcabc.ca` I can target a PID file for Athabasca University objects, and they will delete no problem.

My suggestion would be to make it respect namespace filters by default when fetching PIDs (should be able to get it from the site's Solr query defaults), but allow an option like `--override_namespace_restrictions` if you want to make that possible (or just make it not possible?). When running other operations that target a list of PIDs, maybe check the PID first using `islandora_namespace_accessible()` before the operation is performed?

**Comment by mjordan** [comment]
This sounds reasonable and an excellent feature to have. I have little to no (closer to no) experience with namespace restrictions but I can give it a first stab.

**Comment by bondjimbond** [comment]
I just realized that this is still a problem. I might try fixing it myself if I get a chance, but not sure if I'll do it right.

**Comment by mjordan** [comment]
Merged with a3de8abc41e71e31fdc2ba007551c2cbbc406cc7.
